const data = {
    products: [
      {
        name: "Nike Pro Slim Short‑Sleeve Training Shirt",
        slug: "nike-pro-slim-training-shirt",
        category: "Shirts",
        image: "https://m.media-amazon.com/images/I/81sWuzAsWFL._AC_UL320_.jpg", // 1
        price: 35,
        countInStock: 25,
        brand: "Nike",
        rating: 4.6,
        numReviews: 0,
        description: "Nike Dri‑FIT with mesh ventilation keeps you dry and cool. Lightweight and stretchy with flat‑seam comfort—ideal for intense training sessions.",
        originalPrice: 40,
        isPrime: true,
        hasCoupon: false,
        isFreeShipping: true,
      },
      {
        name: "Nike Pro Dri‑FIT Slim Training Top",
        slug: "nike-pro-dri-fit-top",
        category: "Shirts",
        image: "https://m.media-amazon.com/images/I/51fnPKBNINL._AC_UL320_.jpg", // 2
        price: 32,
        countInStock: 30,
        brand: "Nike",
        rating: 4.5,
        numReviews: 0,
        description: "High‑stretch Dri‑FIT fabric wicks sweat away; mesh over high‑heat zones keeps airflow going. Flat seams feel smooth even during layering.",
        originalPrice: 38,
        isPrime: true,
        hasCoupon: false,
        isFreeShipping: true,
      },
      {
        name: "Adidas Essentials Feel Ready Training Tee",
        slug: "adidas-essentials-feel-ready-tee",
        category: "Shirts",
        image: "https://m.media-amazon.com/images/I/71Xf+hNsifL._AC_UL320_.jpg", // 3
        price: 22,
        countInStock: 40,
        brand: "Adidas",
        rating: 4.6,
        numReviews: 0,
        description: "Regular‑fit AEROREADY tee, made with 70% recycled polyester. Feels dry, light and flexible for training sessions.",
        originalPrice: 25,
        isPrime: true,
        hasCoupon: false,
        isFreeShipping: true,
      },
      {
        name: "Adidas Essentials Stretch Training Tee",
        slug: "adidas-essentials-stretch-tee",
        category: "Shirts",
        image: "https://m.media-amazon.com/images/I/61AK9Fw3+pL._AC_UL320_.jpg", // 4
        price: 20,
        countInStock: 20,
        brand: "Adidas",
        rating: 4.5,
        numReviews: 0,
        description: "Stretchy AEROREADY fabric supports overhead movement; regular fit with recycled materials for eco‑friendly training.",
        originalPrice: 23,
        isPrime: true,
        hasCoupon: false,
        isFreeShipping: false,
      },
      {
        name: "Nike Dri‑FIT Training Pants",
        slug: "nike-dri-fit-training-pants",
        category: "Pants",
        image: "https://m.media-amazon.com/images/I/31bpGXfdIaL._AC_UL320_.jpg", // 5
        price: 50,
        countInStock: 20,
        brand: "Nike",
        rating: 4.5,
        numReviews: 0,
        description: "Lightweight sweatpants with adjustable drawcord waist, zip pockets and moisture‑wicking Dri‑FIT tech—perfect for gym or casual wear.",
        originalPrice: 60,
        isPrime: true,
        hasCoupon: false,
        isFreeShipping: true,
      },
      {
        name: "Adidas Tiro 21 Track Pants",
        slug: "adidas-tiro-21-track-pants",
        category: "Pants",
        image: "https://m.media-amazon.com/images/I/61gTzvMAYyL._AC_UL320_.jpg", // 6
        price: 45,
        countInStock: 15,
        brand: "Adidas",
        rating: 4.6,
        numReviews: 0,
        description: "Classic Tiro 21 style with ankle zips and mesh inserts. Moisture‑managing fabric, optimized for training sessions.",
        originalPrice: 55,
        isPrime: true,
        hasCoupon: true,
        isFreeShipping: false,
      },
      {
        name: "Nike Pro Compression Shorts",
        slug: "nike-pro-compression-shorts",
        category: "Pants",
        image: "https://m.media-amazon.com/images/I/51FVutyd4CL._AC_UL320_.jpg", // 7
        price: 35,
        countInStock: 30,
        brand: "Nike",
        rating: 4.6,
        numReviews: 0,
        description: "Compression‑fit shorts with Dri‑FIT stretch fabric—designed for high‑intensity workouts, muscle support and sweat control.",
        originalPrice: 40,
        isPrime: true,
        hasCoupon: false,
        isFreeShipping: true,
      },
      {
        name: "Adidas Techfit Compression Tee",
        slug: "adidas-techfit-compression-tee",
        category: "Shirts",
        image: "https://m.media-amazon.com/images/I/512dZ3xV61L._AC_UL320_.jpg", // 8
        price: 18,
        countInStock: 30,
        brand: "Adidas",
        rating: 4.4,
        numReviews: 0,
        description: "Compression Techfit tee offers muscle support with sweat‑wicking polyester—built for performance training.",
        originalPrice: 20,
        isPrime: false,
        hasCoupon: true,
        isFreeShipping: false,
      },
    ],
  };
  export default data;
  